// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: query.sql

package sql

import (
	"context"
)

const createLink = `-- name: CreateLink :one
INSERT INTO links (
  short, original
) VALUES (
  $1, $2
)
RETURNING id, short, original
`

type CreateLinkParams struct {
	Short    string
	Original string
}

func (q *Queries) CreateLink(ctx context.Context, arg CreateLinkParams) (Link, error) {
	row := q.db.QueryRow(ctx, createLink, arg.Short, arg.Original)
	var i Link
	err := row.Scan(&i.ID, &i.Short, &i.Original)
	return i, err
}

const getLinkByShort = `-- name: GetLinkByShort :one
SELECT id, short, original FROM links
WHERE short = $1 LIMIT 1
`

func (q *Queries) GetLinkByShort(ctx context.Context, short string) (Link, error) {
	row := q.db.QueryRow(ctx, getLinkByShort, short)
	var i Link
	err := row.Scan(&i.ID, &i.Short, &i.Original)
	return i, err
}
